services:
  # CMS (Payload) - Port 4000
  cms:
    build:
      context: ./apps/cms
      dockerfile: Dockerfile
    container_name: hanotex-cms
    environment:
      - NODE_ENV=production
      - DATABASE_URI=mongodb+srv://office:ZtXXocAefgiuvUcP@chainivodev.rpy80md.mongodb.net/hanotex-test
      - PAYLOAD_SECRET=0e4cd0c22d6eaeaee81a0628
      - PORT=4000
    ports:
      - "4000:4000"
    restart: unless-stopped

  # Web (Next.js) - Port 3000
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: hanotex-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PAYLOAD_API_URL=https://api.hanotex.vn/api
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - cms
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
