services:
  redis:
    image: redis:7-alpine
    container_name: hanotex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: hanotex-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=http://localhost:3001
      # - NEXT_PUBLIC_PAYLOAD_API_URL=http://localhost:4000/api
      - NEXT_PUBLIC_PAYLOAD_API_URL=https://api.hanotex.vn/api
    ports:
      - "3000:3000"
    restart: unless-stopped

  cms:
    build:
      context: ./apps/cms
      dockerfile: Dockerfile
    container_name: hanotex-cms
    environment:
      - NODE_ENV=production
      - DATABASE_URI=mongodb+srv://office:ZtXXocAefgiuvUcP@chainivodev.rpy80md.mongodb.net/hanotex-test
      - PAYLOAD_SECRET=0e4cd0c22d6eaeaee81a0628
      - PORT=4000
    ports:
      - "4000:4000"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
