services:
  postgres:
    image: postgres:15
    container_name: hanotex-postgres
    environment:
      POSTGRES_DB: hanotex-dev-123456
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hanotex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hanotex-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hanotex.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  # web:
  #   build:
  #     context: ./apps/web
  #     dockerfile: Dockerfile
  #   container_name: hanotex-web
  #   environment:
  #     - NODE_ENV=production
  #     - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
  #     - NEXT_PUBLIC_APP_URL=http://localhost:3000
  #     - NEXT_PUBLIC_WS_URL=http://localhost:3001
  #     # - NEXT_PUBLIC_PAYLOAD_API_URL=http://localhost:4000/api
  #     - NEXT_PUBLIC_PAYLOAD_API_URL=http://34.142.238.176:4000/api
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped

  # cms:
  #   build:
  #     context: ./apps/cms
  #     dockerfile: Dockerfile
  #   container_name: hanotex-cms
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URI=postgres://postgres:123456@hanotex-postgres:5432/hanotex-dev
  #     - PAYLOAD_SECRET=0e4cd0c22d6eaeaee81a0628
  #     - PORT=4000
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
