-- HANOTEX Database Schema - Extensions and Types
-- Sàn Giao dịch Công nghệ Hà Nội

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create custom types
CREATE TYPE user_type AS ENUM ('INDIVIDUAL', 'COMPANY', 'RESEARCH_INSTITUTION');
CREATE TYPE user_role AS ENUM ('USER', 'ADMIN', 'MODERATOR', 'SUPPORT');
CREATE TYPE technology_status AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'INACTIVE');
CREATE TYPE auction_status AS ENUM ('SCHEDULED', 'ACTIVE', 'ENDED', 'CANCELLED');
CREATE TYPE auction_type AS ENUM ('ENGLISH', 'DUTCH', 'SEALED_BID');
CREATE TYPE transaction_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');
CREATE TYPE pricing_type AS ENUM ('APPRAISAL', 'ASK', 'AUCTION', 'OFFER');
CREATE TYPE ip_type AS ENUM ('PATENT', 'UTILITY_MODEL', 'INDUSTRIAL_DESIGN', 'TRADEMARK', 'SOFTWARE_COPYRIGHT', 'TRADE_SECRET');